plugins {
    id 'com.android.application'
}

android {
    namespace 'kr.co.iotics.arte'
    compileSdk 34

    defaultConfig {
        applicationId "kr.co.iotics.arte"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug   // 사내 배포용 자체 서명
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
